(function() {function g(a){throw a;}var j=void 0,k=!0,l=null,o=!1;function aa(a){return function(){return this[a]}}function q(a){return function(){return a}}var t,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function u(a){return a!==j}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function w(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return w.apply(l,arguments)}function ja(a,b){function c(){}c.prototype=b.prototype;a.Od=b.prototype;a.prototype=new c};function ka(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function la(){this.Yb=j}
function ma(a,b,c){switch(typeof b){case "string":na(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],ma(a,a.Yb?a.Yb.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
na(f,c),c.push(":"),ma(a,a.Yb?a.Yb.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var oa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function na(a,b){b.push('"',a.replace(pa,function(a){if(a in oa)return oa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return oa[a]=e+b.toString(16)}),'"')};function y(a){if("undefined"!==typeof JSON&&u(JSON.stringify))a=JSON.stringify(a);else{var b=[];ma(new la,a,b);a=b.join("")}return a};function qa(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,z(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};function A(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&g(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function B(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:ra.assert(o,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function C(a,b,c,d){(!d||u(c))&&"function"!=da(c)&&g(Error(B(a,b,d)+"must be a valid function."))}function sa(a,b,c){u(c)&&(!ga(c)||c===l)&&g(Error(B(a,b,k)+"must be a valid context object."))};function D(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function ta(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var ua={},ra={},va=/[\[\].#$\/]/,wa=/[\[\].#$]/;function xa(a){return v(a)&&0!==a.length&&!va.test(a)}function ya(a,b,c){(!c||u(b))&&za(B(a,1,c),b)}
function za(a,b,c,d){c||(c=0);d||(d=[]);u(b)||g(Error(a+"contains undefined"+Aa(d)));"function"==da(b)&&g(Error(a+"contains a function"+Aa(d)+" with contents: "+b.toString()));Ba(b)&&g(Error(a+"contains "+b.toString()+Aa(d)));1E3<c&&g(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));v(b)&&(b.length>10485760/3&&10485760<ua.Pd.Nd(b).length)&&g(Error(a+"contains a string greater than 10485760 utf8 bytes"+Aa(d)+" ('"+b.substring(0,50)+"...')"));if(ga(b))for(var e in b)D(b,
e)&&(".priority"!==e&&(".value"!==e&&!xa(e))&&g(Error(a+"contains an invalid key ("+e+")"+Aa(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),za(a,b[e],c+1,d),d.pop())}function Aa(a){return 0==a.length?"":" in property '"+a.join(".")+"'"}function Ca(a,b){ga(b)||g(Error(B(a,1,o)+" must be an object containing the children to replace."));ya(a,b,o)}
function Da(a,b,c,d){(!d||u(c))&&(c!==l&&!fa(c)&&!v(c))&&g(Error(B(a,b,d)+"must be a valid firebase priority (null or a string.)"))}function Ea(a,b,c){if(!c||u(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:g(Error(B(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}
function Fa(a,b){u(b)&&!xa(b)&&g(Error(B(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}function Ga(a,b){(!v(b)||0===b.length||wa.test(b))&&g(Error(B(a,1,o)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function E(a,b){".info"===G(b)&&g(Error(a+" failed: Can't modify data under /.info/"))};function H(a,b,c,d,e,f,h){this.u=a;this.path=b;this.xa=c;this.ba=d;this.pa=e;this.va=f;this.Oa=h;u(this.ba)&&(u(this.va)&&u(this.xa))&&g("Query: Can't combine startAt(), endAt(), and limit().")}H.prototype.Cc=function(){A("Query.ref",0,0,arguments.length);return new J(this.u,this.path)};H.prototype.ref=H.prototype.Cc;
H.prototype.uc=function(a,b){A("Query.on",2,4,arguments.length);Ea("Query.on",a,o);C("Query.on",2,b,o);var c=Ha("Query.on",arguments[2],arguments[3]);this.u.Fb(this,a,b,c.cancel,c.Z);return b};H.prototype.on=H.prototype.uc;H.prototype.Lb=function(a,b,c){A("Query.off",0,3,arguments.length);Ea("Query.off",a,k);C("Query.off",2,b,k);sa("Query.off",3,c);this.u.Xb(this,a,b,c)};H.prototype.off=H.prototype.Lb;
H.prototype.Bd=function(a,b){function c(h){f&&(f=o,e.Lb(a,c),b.call(d.Z,h))}A("Query.once",2,4,arguments.length);Ea("Query.once",a,o);C("Query.once",2,b,o);var d=Ha("Query.once",arguments[2],arguments[3]),e=this,f=k;this.uc(a,c,function(){e.Lb(a,c);d.cancel&&d.cancel.call(d.Z)})};H.prototype.once=H.prototype.Bd;
H.prototype.wd=function(a){A("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&g("Query.limit: First argument must be a positive integer.");return new H(this.u,this.path,a,this.ba,this.pa,this.va,this.Oa)};H.prototype.limit=H.prototype.wd;H.prototype.Kd=function(a,b){A("Query.startAt",0,2,arguments.length);Da("Query.startAt",1,a,k);Fa("Query.startAt",b);u(a)||(b=a=l);return new H(this.u,this.path,this.xa,a,b,this.va,this.Oa)};H.prototype.startAt=H.prototype.Kd;
H.prototype.qd=function(a,b){A("Query.endAt",0,2,arguments.length);Da("Query.endAt",1,a,k);Fa("Query.endAt",b);return new H(this.u,this.path,this.xa,this.ba,this.pa,a,b)};H.prototype.endAt=H.prototype.qd;function Ia(a){var b={};u(a.ba)&&(b.sp=a.ba);u(a.pa)&&(b.sn=a.pa);u(a.va)&&(b.ep=a.va);u(a.Oa)&&(b.en=a.Oa);u(a.xa)&&(b.l=a.xa);u(a.ba)&&(u(a.pa)&&a.ba===l&&a.pa===l)&&(b.vf="l");return b}H.prototype.Ia=function(){var a=Ja(Ia(this));return"{}"===a?"default":a};
function Ha(a,b,c){var d={};b&&c?(d.cancel=b,C(a,3,d.cancel,k),d.Z=c,sa(a,4,d.Z)):b&&("object"===typeof b&&b!==l?d.Z=b:"function"===typeof b?d.cancel=b:g(Error(B(a,3,k)+"must either be a cancel callback or a context object.")));return d};function K(a){if(a instanceof K)return a;if(1==arguments.length){this.m=a.split("/");for(var b=0,c=0;c<this.m.length;c++)0<this.m[c].length&&(this.m[b]=this.m[c],b++);this.m.length=b;this.W=0}else this.m=arguments[0],this.W=arguments[1]}function G(a){return a.W>=a.m.length?l:a.m[a.W]}function Ka(a){var b=a.W;b<a.m.length&&b++;return new K(a.m,b)}t=K.prototype;t.toString=function(){for(var a="",b=this.W;b<this.m.length;b++)""!==this.m[b]&&(a+="/"+this.m[b]);return a||"/"};
t.parent=function(){if(this.W>=this.m.length)return l;for(var a=[],b=this.W;b<this.m.length-1;b++)a.push(this.m[b]);return new K(a,0)};t.F=function(a){for(var b=[],c=this.W;c<this.m.length;c++)b.push(this.m[c]);if(a instanceof K)for(c=a.W;c<a.m.length;c++)b.push(a.m[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new K(b,0)};t.f=function(){return this.W>=this.m.length};
function La(a,b){var c=G(a);if(c===l)return b;if(c===G(b))return La(Ka(a),Ka(b));g("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}t.contains=function(a){var b=0;if(this.m.length>a.m.length)return o;for(;b<this.m.length;){if(this.m[b]!==a.m[b])return o;++b}return k};function Ma(){this.children={};this.jc=0;this.value=l}function Na(a,b,c){this.ya=a?a:"";this.qb=b?b:l;this.z=c?c:new Ma}function L(a,b){for(var c=b instanceof K?b:new K(b),d=a,e;(e=G(c))!==l;)d=new Na(e,d,ta(d.z.children,e)||new Ma),c=Ka(c);return d}t=Na.prototype;t.j=function(){return this.z.value};function M(a,b){z("undefined"!==typeof b);a.z.value=b;Oa(a)}t.fb=function(){return 0<this.z.jc};t.f=function(){return this.j()===l&&!this.fb()};
t.w=function(a){for(var b in this.z.children)a(new Na(b,this,this.z.children[b]))};function Pa(a,b,c,d){c&&!d&&b(a);a.w(function(a){Pa(a,b,k,d)});c&&d&&b(a)}function Qa(a,b,c){for(a=c?a:a.parent();a!==l;){if(b(a))return k;a=a.parent()}return o}t.path=function(){return new K(this.qb===l?this.ya:this.qb.path()+"/"+this.ya)};t.name=aa("ya");t.parent=aa("qb");
function Oa(a){if(a.qb!==l){var b=a.qb,c=a.ya,d=a.f(),e=D(b.z.children,c);d&&e?(delete b.z.children[c],b.z.jc--,Oa(b)):!d&&!e&&(b.z.children[c]=a.z,b.z.jc++,Oa(b))}};function O(a,b){this.La=a?a:Ra;this.aa=b?b:Sa}function Ra(a,b){return a<b?-1:a>b?1:0}t=O.prototype;t.la=function(a,b){return new O(this.La,this.aa.la(a,b,this.La).copy(l,l,o,l,l))};t.remove=function(a){return new O(this.La,this.aa.remove(a,this.La).copy(l,l,o,l,l))};t.get=function(a){for(var b,c=this.aa;!c.f();){b=this.La(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return l};
function Ta(a,b){for(var c,d=a.aa,e=l;!d.f();){c=a.La(b,d.key);if(0===c){if(d.left.f())return e?e.key:l;for(d=d.left;!d.right.f();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}g(Error("Attempted to find predecessor key for a nonexistent key.  What gives?"))}t.f=function(){return this.aa.f()};t.count=function(){return this.aa.count()};t.kb=function(){return this.aa.kb()};t.Ra=function(){return this.aa.Ra()};t.wa=function(a){return this.aa.wa(a)};t.Ja=function(a){return this.aa.Ja(a)};
t.Pa=function(a){return new Ua(this.aa,a)};function Ua(a,b){this.cd=b;for(this.Jb=[];!a.f();)this.Jb.push(a),a=a.left}function Va(a){if(0===a.Jb.length)return l;var b=a.Jb.pop(),c;c=a.cd?a.cd(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.f();)a.Jb.push(b),b=b.left;return c}function Ya(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=l?c:k;this.left=d!=l?d:Sa;this.right=e!=l?e:Sa}t=Ya.prototype;
t.copy=function(a,b,c,d,e){return new Ya(a!=l?a:this.key,b!=l?b:this.value,c!=l?c:this.color,d!=l?d:this.left,e!=l?e:this.right)};t.count=function(){return this.left.count()+1+this.right.count()};t.f=q(o);t.wa=function(a){return this.left.wa(a)||a(this.key,this.value)||this.right.wa(a)};t.Ja=function(a){return this.right.Ja(a)||a(this.key,this.value)||this.left.Ja(a)};function Za(a){return a.left.f()?a:Za(a.left)}t.kb=function(){return Za(this).key};
t.Ra=function(){return this.right.f()?this.key:this.right.Ra()};t.la=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(l,l,l,e.left.la(a,b,c),l):0===d?e.copy(l,b,l,l,l):e.copy(l,l,l,l,e.right.la(a,b,c));return $a(e)};function ab(a){if(a.left.f())return Sa;!a.left.K()&&!a.left.left.K()&&(a=bb(a));a=a.copy(l,l,l,ab(a.left),l);return $a(a)}
t.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.f()&&(!c.left.K()&&!c.left.left.K())&&(c=bb(c)),c=c.copy(l,l,l,c.left.remove(a,b),l);else{c.left.K()&&(c=cb(c));!c.right.f()&&(!c.right.K()&&!c.right.left.K())&&(c=db(c),c.left.left.K()&&(c=cb(c),c=db(c)));if(0===b(a,c.key)){if(c.right.f())return Sa;d=Za(c.right);c=c.copy(d.key,d.value,l,l,ab(c.right))}c=c.copy(l,l,l,l,c.right.remove(a,b))}return $a(c)};t.K=aa("color");
function $a(a){a.right.K()&&!a.left.K()&&(a=eb(a));a.left.K()&&a.left.left.K()&&(a=cb(a));a.left.K()&&a.right.K()&&(a=db(a));return a}function bb(a){a=db(a);a.right.left.K()&&(a=a.copy(l,l,l,l,cb(a.right)),a=eb(a),a=db(a));return a}function eb(a){var b;b=a.copy(l,l,k,l,a.right.left);return a.right.copy(l,l,a.color,b,l)}function cb(a){var b;b=a.copy(l,l,k,a.left.right,l);return a.left.copy(l,l,a.color,l,b)}
function db(a){var b,c;b=a.left.copy(l,l,!a.left.color,l,l);c=a.right.copy(l,l,!a.right.color,l,l);return a.copy(l,l,!a.color,b,c)}function fb(){}t=fb.prototype;t.copy=function(){return this};t.la=function(a,b){return new Ya(a,b,j,j,j)};t.remove=function(){return this};t.get=q(l);t.count=q(0);t.f=q(k);t.wa=q(o);t.Ja=q(o);t.kb=q(l);t.Ra=q(l);t.K=q(o);var Sa=new fb;var gb=Array.prototype,hb=gb.forEach?function(a,b,c){gb.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ib=gb.map?function(a,b,c){return gb.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};function jb(){};function kb(){this.B=[];this.ic=[];this.md=[];this.Pb=[];this.Pb[0]=128;for(var a=1;64>a;++a)this.Pb[a]=0;this.reset()}ja(kb,jb);kb.prototype.reset=function(){this.B[0]=1732584193;this.B[1]=4023233417;this.B[2]=2562383102;this.B[3]=271733878;this.B[4]=3285377520;this.Lc=this.gb=0};
function lb(a,b){var c;c||(c=0);for(var d=a.md,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}c=a.B[0];for(var h=a.B[1],i=a.B[2],m=a.B[3],n=a.B[4],p,e=0;80>e;e++)40>e?20>e?(f=m^h&(i^m),p=1518500249):(f=h^i^m,p=1859775393):60>e?(f=h&i|m&(h|i),p=2400959708):(f=h^i^m,p=3395469782),f=(c<<5|c>>>27)+f+n+p+d[e]&4294967295,n=m,m=i,i=(h<<30|h>>>2)&4294967295,h=c,c=f;a.B[0]=a.B[0]+c&4294967295;a.B[1]=a.B[1]+h&
4294967295;a.B[2]=a.B[2]+i&4294967295;a.B[3]=a.B[3]+m&4294967295;a.B[4]=a.B[4]+n&4294967295}kb.prototype.update=function(a,b){u(b)||(b=a.length);var c=this.ic,d=this.gb,e=0;if(v(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(lb(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(lb(this,c),d=0);this.gb=d;this.Lc+=b};function mb(){this.Ka={};this.length=0}mb.prototype.setItem=function(a,b){D(this.Ka,a)||(this.length+=1);this.Ka[a]=b};mb.prototype.getItem=function(a){return D(this.Ka,a)?this.Ka[a]:l};mb.prototype.removeItem=function(a){D(this.Ka,a)&&(this.length-=1,delete this.Ka[a])};var nb=l;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),nb=sessionStorage}catch(ob){nb=new mb}else nb=new mb;function pb(a,b,c,d){this.host=a.toLowerCase();this.Zb=b;this.lb=c;this.da=d||nb.getItem(a)||this.host}function qb(a,b){b!==a.da&&(a.da=b,"s-"===a.da.substr(0,2)&&nb.setItem(a.host,a.da))}pb.prototype.toString=function(){return(this.Zb?"https://":"http://")+this.host};var rb,sb,tb,ub;function vb(){return ba.navigator?ba.navigator.userAgent:l}ub=tb=sb=rb=o;var wb;if(wb=vb()){var xb=ba.navigator;rb=0==wb.indexOf("Opera");sb=!rb&&-1!=wb.indexOf("MSIE");tb=!rb&&-1!=wb.indexOf("WebKit");ub=!rb&&!tb&&"Gecko"==xb.product}var yb=sb,zb=ub,Ab=tb;var Bb;if(rb&&ba.opera){var Cb=ba.opera.version;"function"==typeof Cb&&Cb()}else zb?Bb=/rv\:([^\);]+)(\)|;)/:yb?Bb=/MSIE\s+([^\);]+)(\)|;)/:Ab&&(Bb=/WebKit\/(\S+)/),Bb&&Bb.exec(vb());var Db=l,Eb=l;
function Fb(a,b){ea(a)||g(Error("encodeByteArray takes an array as a parameter"));if(!Db){Db={};Eb={};for(var c=0;65>c;c++)Db[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Eb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Eb:Db,d=[],e=0;e<a.length;e+=3){var f=a[e],h=e+1<a.length,i=h?a[e+1]:0,m=e+2<a.length,n=m?a[e+2]:0,p=f>>2,f=(f&3)<<4|i>>4,i=(i&15)<<2|n>>6,n=n&63;m||(n=64,h||(i=64));d.push(c[p],c[f],c[i],c[n])}return d.join("")}
;var Gb,Hb=1;Gb=function(){return Hb++};function z(a,b){a||g(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Ib(a){var b=qa(a),a=new kb;a.update(b);var b=[],c=8*a.Lc;56>a.gb?a.update(a.Pb,56-a.gb):a.update(a.Pb,64-(a.gb-56));for(var d=63;56<=d;d--)a.ic[d]=c&255,c/=256;lb(a,a.ic);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.B[d]>>e&255;return Fb(b)}
function Jb(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Jb.apply(l,arguments[b]):"object"===typeof arguments[b]?a+y(arguments[b]):a+arguments[b],a+=" ";return a}var Kb=l,Lb=k;function P(){Lb===k&&(Lb=o,Kb===l&&"true"===nb.getItem("logging_enabled")&&Mb(k));if(Kb){var a=Jb.apply(l,arguments);Kb(a)}}function Nb(a){return function(){P(a,arguments)}}
function Ob(){if("undefined"!==typeof console){var a="FIREBASE INTERNAL ERROR: "+Jb.apply(l,arguments);"undefined"!==typeof console.error?console.error(a):console.log(a)}}function Pb(){var a=Jb.apply(l,arguments);g(Error("FIREBASE FATAL ERROR: "+a))}function Qb(){if("undefined"!==typeof console){var a="FIREBASE WARNING: "+Jb.apply(l,arguments);"undefined"!==typeof console.warn?console.warn(a):console.log(a)}}
function Ba(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}function Rb(a,b){return a!==b?a===l?-1:b===l?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Sb(a,b){if(b&&a in b)return b[a];g(Error("Missing required key ("+a+") in object: "+y(b)))}function Ja(a){if("object"!==typeof a||a===l)return y(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=y(b[d]),c+=":",c+=Ja(a[b[d]]);return c+"}"}
function Tb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c}function Ub(a,b){if("array"==da(a))for(var c=0;c<a.length;++c)b(c,a[c]);else Vb(a,b)}
function Wb(a){z(!Ba(a));var b,c,d,e;0===a?(d=c=0,b=-Infinity===1/a?1:0):(b=0>a,a=Math.abs(a),a>=Math.pow(2,-1022)?(d=Math.min(Math.floor(Math.log(a)/Math.LN2),1023),c=d+1023,d=Math.round(a*Math.pow(2,52-d)-Math.pow(2,52))):(c=0,d=Math.round(a/Math.pow(2,-1074))));e=[];for(a=52;a;a-=1)e.push(d%2?1:0),d=Math.floor(d/2);for(a=11;a;a-=1)e.push(c%2?1:0),c=Math.floor(c/2);e.push(b?1:0);e.reverse();b=e.join("");c="";for(a=0;64>a;a+=8)d=parseInt(b.substr(a,8),2).toString(16),1===d.length&&(d="0"+d),c+=d;
return c.toLowerCase()};function Xb(a,b){this.D=a;z(this.D!==l,"LeafNode shouldn't be created with null value.");this.Ta="undefined"!==typeof b?b:l}t=Xb.prototype;t.J=q(k);t.k=aa("Ta");t.Db=function(a){return new Xb(this.D,a)};t.O=function(){return Q};t.N=function(a){return G(a)===l?this:Q};t.ca=q(l);t.H=function(a,b){return(new R(new O,this.Ta)).H(a,b)};t.sa=function(a,b){var c=G(a);return c===l?b:this.H(c,Q.sa(Ka(a),b))};t.f=q(o);t.Kb=q(0);
t.T=function(a){return a&&this.k()!==l?{".value":this.j(),".priority":this.k()}:this.j()};t.hash=function(){var a="";this.k()!==l&&(a+="priority:"+Yb(this.k())+":");var b=typeof this.D,a=a+(b+":"),a="number"===b?a+Wb(this.D):a+this.D;return Ib(a)};t.j=aa("D");t.toString=function(){return"string"===typeof this.D?'"'+this.D+'"':this.D};function R(a,b){this.n=a||new O;this.Ta="undefined"!==typeof b?b:l}t=R.prototype;t.J=q(o);t.k=aa("Ta");t.Db=function(a){return new R(this.n,a)};t.H=function(a,b){var c=this.n.remove(a);b&&b.f()&&(b=l);b!==l&&(c=c.la(a,b));return b&&b.k()!==l?new $b(c,l,this.Ta):new R(c,this.Ta)};t.sa=function(a,b){var c=G(a);if(c===l)return b;var d=this.O(c).sa(Ka(a),b);return this.H(c,d)};t.f=function(){return this.n.f()};t.Kb=function(){return this.n.count()};var ac=/^\d+$/;t=R.prototype;
t.T=function(a){if(this.f())return l;var b={},c=0,d=0,e=k;this.w(function(f,h){b[f]=h.T(a);c++;e&&ac.test(f)?d=Math.max(d,Number(f)):e=o});if(!a&&e&&d<2*c){var f=[],h;for(h in b)f[h]=b[h];return f}a&&this.k()!==l&&(b[".priority"]=this.k());return b};t.hash=function(){var a="";this.k()!==l&&(a+="priority:"+Yb(this.k())+":");this.w(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Ib(a)};t.O=function(a){a=this.n.get(a);return a===l?Q:a};
t.N=function(a){var b=G(a);return b===l?this:this.O(b).N(Ka(a))};t.ca=function(a){return Ta(this.n,a)};t.Tc=function(){return this.n.kb()};t.Uc=function(){return this.n.Ra()};t.w=function(a){return this.n.wa(a)};t.oc=function(a){return this.n.Ja(a)};t.Pa=function(){return this.n.Pa()};t.toString=function(){var a="{",b=k;this.w(function(c,d){b?b=o:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var Q=new R(new O);function $b(a,b,c){R.call(this,a,c);b===l&&(b=new O(bc),a.wa(function(a,c){b=b.la({name:a,ma:c.k()},c)}));this.oa=b}ja($b,R);t=$b.prototype;t.H=function(a,b){var c=this.O(a),d=this.n,e=this.oa;c!==l&&(d=d.remove(a),e=e.remove({name:a,ma:c.k()}));b&&b.f()&&(b=l);b!==l&&(d=d.la(a,b),e=e.la({name:a,ma:b.k()},b));return new $b(d,e,this.k())};t.ca=function(a,b){var c=Ta(this.oa,{name:a,ma:b.k()});return c?c.name:l};t.w=function(a){return this.oa.wa(function(b,c){return a(b.name,c)})};
t.oc=function(a){return this.oa.Ja(function(b,c){return a(b.name,c)})};t.Pa=function(){return this.oa.Pa(function(a,b){return{key:a.name,value:b}})};t.Tc=function(){return this.oa.f()?l:this.oa.kb().name};t.Uc=function(){return this.oa.f()?l:this.oa.Ra().name};function S(a,b){if("object"!==typeof a)return new Xb(a,b);if(a===l)return Q;var c=l;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);z(c===l||"string"===typeof c||"number"===typeof c);if(".value"in a&&a[".value"]!==l)return new Xb(a[".value"],c);if(a instanceof Array){var c=new R(new O,c),d;for(d in a)if(D(a,d)&&"."!==d.substring(0,1)){var e=S(a[d]);if(e.J()||!e.f())c=c.H(d,e)}return c}var f=[],h={},i=o;Ub(a,function(b,c){if("string"!==typeof c||"."!==c.substring(0,1)){var d=S(a[c]);
d.f()||(i=i||d.k()!==l,f.push({name:c,ma:d.k()}),h[c]=d)}});d=cc(f,h,o);return i?(e=cc(f,h,k),new $b(d,e,c)):new R(d,c)}var dc=Math.log(2);function ec(a){this.count=parseInt(Math.log(a+1)/dc);this.Pc=this.count-1;this.nd=a+1&parseInt(Array(this.count+1).join("1"),2)}
function cc(a,b,c){function d(d,f){var h=n-d,p=n;n-=d;var s=a[h].name,h=new Ya(c?a[h]:s,b[s],f,l,e(h+1,p));i?i.left=h:m=h;i=h}function e(d,f){var h=f-d;if(0==h)return l;if(1==h){var h=a[d].name,i=c?a[d]:h;return new Ya(i,b[h],o,l,l)}var i=parseInt(h/2)+d,m=e(d,i),n=e(i+1,f),h=a[i].name,i=c?a[i]:h;return new Ya(i,b[h],o,m,n)}var f=c?bc:fc;a.sort(f);var h;h=new ec(a.length);for(var i=l,m=l,n=a.length,p=0;p<h.count;++p){var r=!(h.nd&1<<h.Pc);h.Pc--;var s=Math.pow(2,h.count-(p+1));r?d(s,o):(d(s,o),d(s,
k))}h=m;return h!==l?new O(c?f:l,h):new O(c?f:l)}function bc(a,b){return Rb(a.ma,b.ma)||(a.name!==b.name?a.name<b.name?-1:1:0)}function fc(a,b){return a.name!==b.name?a.name<b.name?-1:1:0}function Yb(a){return"number"===typeof a?"number:"+Wb(a):"string:"+a};function T(a,b){this.z=a;this.Wb=b}T.prototype.T=function(){A("Firebase.DataSnapshot.val",0,0,arguments.length);return this.z.T()};T.prototype.val=T.prototype.T;T.prototype.rd=function(){A("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.z.T(k)};T.prototype.exportVal=T.prototype.rd;T.prototype.F=function(a){A("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Ga("Firebase.DataSnapshot.child",a);var b=new K(a),c=this.Wb.F(b);return new T(this.z.N(b),c)};
T.prototype.child=T.prototype.F;T.prototype.qc=function(a){A("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Ga("Firebase.DataSnapshot.hasChild",a);var b=new K(a);return!this.z.N(b).f()};T.prototype.hasChild=T.prototype.qc;T.prototype.k=function(){A("Firebase.DataSnapshot.getPriority",0,0,arguments.length);return this.z.k()};T.prototype.getPriority=T.prototype.k;
T.prototype.forEach=function(a){A("Firebase.DataSnapshot.forEach",1,1,arguments.length);C("Firebase.DataSnapshot.forEach",1,a,o);if(this.z.J())return o;var b=this;return this.z.w(function(c,d){return a(new T(d,b.Wb.F(c)))})};T.prototype.forEach=T.prototype.forEach;T.prototype.fb=function(){A("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.z.J()?o:!this.z.f()};T.prototype.hasChildren=T.prototype.fb;
T.prototype.name=function(){A("Firebase.DataSnapshot.name",0,0,arguments.length);return this.Wb.name()};T.prototype.name=T.prototype.name;T.prototype.Kb=function(){A("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.z.Kb()};T.prototype.numChildren=T.prototype.Kb;T.prototype.Cc=function(){A("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.Wb};T.prototype.ref=T.prototype.Cc;function gc(a){this.yc=a;this.Rb=[];this.Na=0;this.kc=-1;this.Ga=l};function Vb(a,b){for(var c in a)b.call(j,a[c],c,a)}function hc(a){var b={},c;for(c in a)b[c]=a[c];return b};function ic(){this.ab={}}function jc(a,b,c){u(c)||(c=1);D(a.ab,b)||(a.ab[b]=0);a.ab[b]+=c}ic.prototype.get=function(){return hc(this.ab)};function kc(a){this.od=a;this.Ib=l}kc.prototype.get=function(){var a=this.od.get(),b=hc(a);if(this.Ib)for(var c in this.Ib)b[c]-=this.Ib[c];this.Ib=a;return b};function lc(a,b){this.Ic={};this.bc=new kc(a);this.o=b;setTimeout(w(this.ad,this),10+6E4*Math.random())}lc.prototype.ad=function(){var a=this.bc.get(),b={},c=o,d;for(d in a)0<a[d]&&D(this.Ic,d)&&(b[d]=a[d],c=k);c&&(a=this.o,a.U&&(b={c:b},a.e("reportStats",b),a.Aa("s",b)));setTimeout(w(this.ad,this),6E5*Math.random())};var mc={},nc={};function oc(a){a=a.toString();mc[a]||(mc[a]=new ic);return mc[a]};var pc=l;"undefined"!==typeof MozWebSocket?pc=MozWebSocket:"undefined"!==typeof WebSocket&&(pc=WebSocket);function qc(a,b,c){this.lc=a;this.e=Nb(this.lc);this.frames=this.ib=l;this.Kc=0;this.X=oc(b);this.Ma=(b.Zb?"wss://":"ws://")+b.da+"/.ws?v=5";b.host!==b.da&&(this.Ma=this.Ma+"&ns="+b.lb);c&&(this.Ma=this.Ma+"&s="+c)}var rc;
qc.prototype.open=function(a,b){this.fa=b;this.Ad=a;this.e("websocket connecting to "+this.Ma);this.V=new pc(this.Ma);this.bb=o;var c=this;this.V.onopen=function(){c.e("Websocket connected.");c.bb=k};this.V.onclose=function(){c.e("Websocket connection was disconnected.");c.V=l;c.Ha()};this.V.onmessage=function(a){if(c.V!==l)if(a=a.data,jc(c.X,"bytes_received",a.length),sc(c),c.frames!==l)tc(c,a);else{a:{z(c.frames===l,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.Kc=
b;c.frames=[];a=l;break a}}c.Kc=1;c.frames=[]}a!==l&&tc(c,a)}};this.V.onerror=function(a){c.e("WebSocket error.  Closing connection.");a.data&&c.e(a.data);c.Ha()}};qc.prototype.start=function(){};qc.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&pc!==l&&!rc};function tc(a,b){a.frames.push(b);if(a.frames.length==a.Kc){var c=a.frames.join("");a.frames=l;c="undefined"!==typeof JSON&&u(JSON.parse)?JSON.parse(c):ka(c);a.Ad(c)}}
qc.prototype.send=function(a){sc(this);a=y(a);jc(this.X,"bytes_sent",a.length);a=Tb(a,16384);1<a.length&&this.V.send(String(a.length));for(var b=0;b<a.length;b++)this.V.send(a[b])};qc.prototype.Ab=function(){this.Ea=k;this.ib&&(clearTimeout(this.ib),this.ib=l);this.V&&(this.V.close(),this.V=l)};qc.prototype.Ha=function(){this.Ea||(this.e("WebSocket is closing itself"),this.Ab(),this.fa&&(this.fa(this.bb),this.fa=l))};qc.prototype.close=function(){this.Ea||(this.e("WebSocket is being closed"),this.Ab())};
function sc(a){clearTimeout(a.ib);a.ib=setInterval(function(){a.V.send("0");sc(a)},45E3)};function uc(){this.set={}}t=uc.prototype;t.add=function(a,b){this.set[a]=b!==l?b:k};t.contains=function(a){return D(this.set,a)};t.get=function(a){return this.contains(a)?this.set[a]:j};t.remove=function(a){delete this.set[a]};t.f=function(){var a;a:{for(a in this.set){a=o;break a}a=k}return a};t.count=function(){var a=0,b;for(b in this.set)a++;return a};function U(a,b){for(var c in a.set)D(a.set,c)&&b(c,a.set[c])}t.keys=function(){var a=[],b;for(b in this.set)D(this.set,b)&&a.push(b);return a};var vc="pLPCommand",wc="pRTLPCB";function xc(a,b,c){this.lc=a;this.e=Nb(a);this.Md=b;this.X=oc(b);this.ac=c;this.bb=o;this.Eb=function(a){b.host!==b.da&&(a.ns=b.lb);var c=[],f;for(f in a)a.hasOwnProperty(f)&&c.push(f+"="+a[f]);return(b.Zb?"https://":"http://")+b.da+"/.lp?"+c.join("&")}}var yc,zc;
xc.prototype.open=function(a,b){function c(){if(!d.Ea){d.ga=new Ac(function(a,b,c,e,f){jc(d.X,"bytes_received",y(arguments).length);if(d.ga)if(d.Ca&&(clearTimeout(d.Ca),d.Ca=l),d.bb=k,"start"==a)d.id=b,d.$c=c;else if("close"===a)if(b){d.ga.$b=o;var h=d.Xc;h.kc=b;h.Ga=function(){d.Ha()};h.kc<h.Na&&(h.Ga(),h.Ga=l)}else d.Ha();else g(Error("Unrecognized command received: "+a))},function(a,b){jc(d.X,"bytes_received",y(arguments).length);var c=d.Xc;for(c.Rb[a]=b;c.Rb[c.Na];){var e=c.Rb[c.Na];delete c.Rb[c.Na];
for(var f=0;f<e.length;++f)e[f]&&c.yc(e[f]);if(c.Na===c.kc){c.Ga&&(clearTimeout(c.Ga),c.Ga(),c.Ga=l);break}c.Na++}},function(){d.Ha()},d.Eb);var a={start:"t"};a.ser=Math.floor(1E8*Math.random());d.ga.dc&&(a.cb=d.ga.dc);a.v="5";d.ac&&(a.s=d.ac);a=d.Eb(a);d.e("Connecting via long-poll to "+a);Bc(d.ga,a,function(){})}}this.Oc=0;this.P=b;this.Xc=new gc(a);this.Ea=o;var d=this;this.Ca=setTimeout(function(){d.e("Timed out trying to connect.");d.Ha();d.Ca=l},3E4);if("complete"===document.readyState)c();
else{var e=o,f=function(){document.body?e||(e=k,c()):setTimeout(f,10)};document.addEventListener?(document.addEventListener("DOMContentLoaded",f,o),window.addEventListener("load",f,o)):document.attachEvent&&(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&f()},o),window.attachEvent("onload",f,o))}};
xc.prototype.start=function(){var a=this.ga,b=this.$c;a.yd=this.id;a.zd=b;for(a.gc=k;Cc(a););a=this.id;b=this.$c;this.Sa=document.createElement("iframe");var c={dframe:"t"};c.id=a;c.pw=b;a=this.Eb(c);this.Sa.src=a;this.Sa.style.display="none";document.body.appendChild(this.Sa)};xc.isAvailable=function(){return!zc&&!("object"===typeof window&&window.chrome&&window.chrome.extension&&!/^chrome/.test(window.location.href))&&(yc||k)};
xc.prototype.Ab=function(){this.Ea=k;this.ga&&(this.ga.close(),this.ga=l);this.Sa&&(document.body.removeChild(this.Sa),this.Sa=l);this.Ca&&(clearTimeout(this.Ca),this.Ca=l)};xc.prototype.Ha=function(){this.Ea||(this.e("Longpoll is closing itself"),this.Ab(),this.P&&(this.P(this.bb),this.P=l))};xc.prototype.close=function(){this.Ea||(this.e("Longpoll is being closed."),this.Ab())};
xc.prototype.send=function(a){a=y(a);jc(this.X,"bytes_sent",a.length);for(var a=qa(a),a=Fb(a,k),a=Tb(a,1840),b=0;b<a.length;b++){var c=this.ga;c.sb.push({Gd:this.Oc,Ld:a.length,Qc:a[b]});c.gc&&Cc(c);this.Oc++}};
function Ac(a,b,c,d){this.Eb=d;this.fa=c;this.Ac=new uc;this.sb=[];this.mc=Math.floor(1E8*Math.random());this.$b=k;this.dc=Gb();window[vc+this.dc]=a;window[wc+this.dc]=b;a=document.createElement("iframe");a.style.display="none";if(document.body){document.body.appendChild(a);try{a.contentWindow.document||P("No IE domain setting required")}catch(e){a.src="javascript:void((function(){document.open();document.domain='"+document.domain+"';document.close();})())"}}else g("Document body has not initialized. Wait to initialize Firebase until after the document is ready.");
a.contentDocument?a.ua=a.contentDocument:a.contentWindow?a.ua=a.contentWindow.document:a.document&&(a.ua=a.document);this.$=a;a="";"javascript:"===this.$.src.substr(0,11)&&(a='<script>document.domain="'+document.domain+'";<\/script>');a="<html><body>"+a+"</body></html>";try{this.$.ua.open(),this.$.ua.write(a),this.$.ua.close()}catch(f){P("frame writing exception"),f.stack&&P(f.stack),P(f)}}
Ac.prototype.close=function(){this.gc=o;if(this.$){this.$.ua.body.innerHTML="";var a=this;setTimeout(function(){a.$!==l&&(document.body.removeChild(a.$),a.$=l)},0)}var b=this.fa;b&&(this.fa=l,b())};
function Cc(a){if(a.gc&&a.$b&&a.Ac.count()<(0<a.sb.length?2:1)){a.mc++;var b={};b.id=a.yd;b.pw=a.zd;b.ser=a.mc;for(var b=a.Eb(b),c="",d=0;0<a.sb.length;)if(1870>=a.sb[0].Qc.length+30+c.length){var e=a.sb.shift(),c=c+"&seg"+d+"="+e.Gd+"&ts"+d+"="+e.Ld+"&d"+d+"="+e.Qc;d++}else break;var b=b+c,f=a.mc;a.Ac.add(f);var h=function(){a.Ac.remove(f);Cc(a)},i=setTimeout(h,25E3);Bc(a,b,function(){clearTimeout(i);h()});return k}return o}
function Bc(a,b,c){setTimeout(function(){try{if(a.$b){var d=a.$.ua.createElement("script");d.type="text/javascript";d.async=k;d.src=b;d.onload=d.onreadystatechange=function(){var a=d.readyState;if(!a||"loaded"===a||"complete"===a)d.onload=d.onreadystatechange=l,d.parentNode&&d.parentNode.removeChild(d),c()};d.onerror=function(){P("Long-poll script failed to load: "+b);a.$b=o;a.close()};a.$.ua.body.appendChild(d)}}catch(e){}},1)};function Dc(){var a=[];Ub(Ec,function(b,c){c&&c.isAvailable()&&a.push(c)});this.cc=a}var Ec=[xc,{isAvailable:q(o)},qc];function Fc(a,b,c,d,e,f){this.id=a;this.e=Nb("c:"+this.id+":");this.yc=c;this.ob=d;this.P=e;this.xc=f;this.R=b;this.Qb=[];this.Nc=0;this.Mc=new Dc;this.qa=0;this.e("Connection created");Gc(this)}function Gc(a){var b;var c=a.Mc;0<c.cc.length?b=c.cc[0]:g(Error("No transports available"));a.I=new b("c:"+a.id+":"+a.Nc++,a.R);var d=Jc(a,a.I),e=Kc(a,a.I);a.Bb=a.I;a.yb=a.I;a.A=l;setTimeout(function(){a.I&&a.I.open(d,e)},0)}
function Kc(a,b){return function(c){b===a.I?(a.I=l,!c&&0===a.qa?(a.e("Realtime connection failed."),"s-"===a.R.da.substr(0,2)&&(nb.removeItem(a.R.lb),a.R.da=a.R.host)):1===a.qa&&a.e("Realtime connection lost."),a.close()):b===a.A?(c=a.A,a.A=l,(a.Bb===c||a.yb===c)&&a.close()):a.e("closing an old connection")}}
function Jc(a,b){return function(c){if(2!=a.qa)if(b===a.yb){var d=Sb("t",c),c=Sb("d",c);if("c"==d){if(d=Sb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,f=c.h;a.ac=c.s;qb(a.R,f);if(0==a.qa&&(a.I.start(),c=a.I,a.e("Realtime connection established."),a.I=c,a.qa=1,a.ob&&(a.ob(d),a.ob=l),"5"!==e&&Qb("Protocol version mismatch detected"),c=1<a.Mc.cc.length?a.Mc.cc[1]:l))a.A=new c("c:"+a.id+":"+a.Nc++,a.R,a.ac),a.A.open(Jc(a,a.A),Kc(a,a.A))}else if("n"===d){a.e("recvd end transmission on primary");
a.yb=a.A;for(c=0;c<a.Qb.length;++c)a.Nb(a.Qb[c]);a.Qb=[];Lc(a)}else"s"===d?(a.e("Connection shutdown command received. Shutting down..."),a.xc&&(a.xc(c),a.xc=l),a.P=l,a.close()):"r"===d?(a.e("Reset packet received.  New host: "+c),qb(a.R,c),1===a.qa?a.close():(Mc(a),Gc(a))):Ob("Unknown control packet command: "+d)}else"d"==d&&a.Nb(c)}else b===a.A?(d=Sb("t",c),c=Sb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.A.start(),a.e("sending client ack on secondary"),a.A.send({t:"c",d:{t:"a",d:{}}}),a.e("Ending transmission on primary"),
a.I.send({t:"c",d:{t:"n",d:{}}}),a.Bb=a.A,Lc(a)):"r"===c&&(a.e("Got a reset on secondary, closing it"),a.A.close(),(a.Bb===a.A||a.yb===a.A)&&a.close())):"d"==d?a.Qb.push(c):g(Error("Unknown protocol layer: "+d))):a.e("message on old connection")}}Fc.prototype.Ec=function(a){a={t:"d",d:a};1!==this.qa&&g("Connection is not connected");this.Bb.send(a)};function Lc(a){a.Bb===a.A&&a.yb===a.A&&(a.e("cleaning up and promoting a connection: "+a.A.lc),a.I=a.A,a.A=l)}Fc.prototype.Nb=function(a){this.yc(a)};
Fc.prototype.close=function(){2!==this.qa&&(this.e("Closing realtime connection."),this.qa=2,Mc(this),this.P&&(this.P(),this.P=l))};function Mc(a){a.e("Shutting down all connections");a.I&&(a.I.close(),a.I=l);a.A&&(a.A.close(),a.A=l)};function Nc(a,b,c,d,e){this.id=Oc++;this.e=Nb("p:"+this.id+":");this.zb=k;this.ea={};this.S=[];this.pb=0;this.nb=[];this.U=o;this.Vb=1E3;this.Ob=b||ca;this.Mb=c||ca;this.mb=d||ca;this.zc=e||ca;this.R=a;this.Dc=l;this.Sb=[];this.wb={};this.Fd=0;this.jb=this.Wc=l;setTimeout(w(this.Rc,this),0)}var Oc=0,Pc=0;t=Nc.prototype;t.Aa=function(a,b,c){var d=++this.Fd,a={r:d,a:a,b:b};this.e(y(a));this.U?this.ub.Ec(a):this.Sb.push(a);c&&(this.wb[d]=c)};
function Qc(a,b,c,d,e){a.e("Listen on "+b+" for "+c);var f={p:b},d=ib(d,function(a){return Ia(a)});"{}"!==c&&(f.q=d);a.Aa("l",f,function(d){a.e("listen response",d);d=d.s;"ok"!==d&&Rc(a,b,c);e&&e(d)})}t.$a=function(a,b,c){this.Da={pd:a,Sc:o,ia:b,Gb:c};this.e("Authenticating using credential: "+this.Da);Sc(this)};t.Cb=function(){delete this.Da;this.mb(o);this.U&&this.Aa("unauth",{})};
function Sc(a){var b=a.Da;a.U&&b&&a.Aa("auth",{cred:b.pd},function(c){var d=c.s,c=c.d||"error";"ok"!==d&&a.Da===b&&delete a.Da;b.Sc?"ok"!==d&&b.Gb&&b.Gb(d,c):(b.Sc=k,b.ia&&b.ia(d,c));a.mb("ok"===d)})}t.hd=function(a,b,c){a=a.toString();Rc(this,a,b)&&this.U&&(this.e("Unlisten on "+a+" for "+b),a={p:a},c=ib(c,function(a){return Ia(a)}),"{}"!==b&&(a.q=c),this.Aa("u",a))};function Tc(a,b,c,d){a.U?Uc(a,"o",b,c,d):a.nb.push({Bc:b,action:"o",data:c,C:d})}
t.wc=function(a,b){this.U?Uc(this,"oc",a,l,b):this.nb.push({Bc:a,action:"oc",data:l,C:b})};function Uc(a,b,c,d,e){c={p:c,d:d};a.e("onDisconnect "+b,c);a.Aa(b,c,function(a){e&&setTimeout(function(){e(a.s)},0)})}t.put=function(a,b,c,d){Vc(this,"p",a,b,c,d)};function Vc(a,b,c,d,e,f){c={p:c,d:d};u(f)&&(c.h=f);a.S.push({action:b,bd:c,C:e});a.pb++;b=a.S.length-1;a.U&&Wc(a,b)}
function Wc(a,b){var c=a.S[b].action,d=a.S[b].bd,e=a.S[b].C;a.S[b].Cd=a.U;a.Aa(c,d,function(d){a.e(c+" response",d);delete a.S[b];a.pb--;0===a.pb&&(a.S=[]);e&&e(d.s)})}
t.Nb=function(a){if("r"in a){this.e("from server: "+y(a));var b=a.r,c=this.wb[b];c&&(delete this.wb[b],c(a.b))}else"error"in a&&g("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,a=a.b,this.e("handleServerMessage",b,a),"d"===b?this.Ob(a.p,a.d):"m"===b?this.Ob(a.p,a.d,k):"c"===b?(b=a.p,a=(a=a.q)?ib(a,function(a){return Ja(a)}).join("$"):"{}",(a=Rc(this,b,a))&&a.C&&a.C("permission_denied")):"ac"===b?(b=a.s,a=a.d,c=this.Da,delete this.Da,c&&c.Gb&&c.Gb(b,a),this.mb(o)):"sd"===b?this.Dc?this.Dc(a):
"msg"in a&&"undefined"!==typeof console&&console.log("FIREBASE: "+a.msg.replace("\n","\nFIREBASE: ")):Ob("Unrecognized action received from server: "+y(b)+"\nAre you using the latest client?"))};
t.ob=function(a){this.e("connection ready");this.U=k;this.jb=(new Date).getTime();this.zc({serverTimeOffset:a-(new Date).getTime()});for(a=0;a<this.Sb.length;a++)this.ub.Ec(this.Sb[a]);this.Sb=[];Sc(this);for(a=0;a<this.S.length;a++)this.S[a]&&Wc(this,a);for(var b in this.ea)for(var c in this.ea[b])a=this.ea[b][c],Qc(this,b,c,a.Ua,a.C);for(;this.nb.length;)b=this.nb.shift(),Uc(this,b.action,b.Bc,b.data,b.C);this.Mb(k)};
t.Yc=function(){this.U=o;this.e("data client disconnected");for(var a=w(function(){this.Rc()},this),b=0;b<this.S.length;b++){var c=this.S[b];c&&("h"in c.bd&&c.Cd)&&(c.C&&c.C("disconnect"),delete this.S[b],this.pb--)}0===this.pb&&(this.S=[]);if(this.zb)this.jb&&(3E4<(new Date).getTime()-this.jb&&(this.Vb=1E3),this.jb=l),b=Math.max(0,this.Vb-((new Date).getTime()-this.Wc)),b*=Math.random(),this.e("Trying to reconnect in "+b+"ms"),setTimeout(a,b),this.Vb=Math.min(3E5,1.3*this.Vb);else{for(var d in this.wb)delete this.wb[d];
this.dd=function(){setTimeout(a,0)}}this.Mb(o)};t.Rc=function(){if(this.zb){this.e("Making a connection attempt");this.Wc=(new Date).getTime();this.jb=l;var a=w(this.Nb,this),b=w(this.ob,this),c=w(this.Yc,this),d=this.id+":"+Pc++,e=this;this.ub=new Fc(d,this.R,a,b,c,function(a){e.zb=o;g(Error(a))})}};t.Qa=function(){this.zb=o;this.ub?this.ub.close():this.Yc()};t.xb=function(){this.zb=k;this.dd();this.dd=j};
function Rc(a,b,c){b=(new K(b)).toString();c||(c="{}");var d=a.ea[b][c];delete a.ea[b][c];return d};function Xc(){this.n=this.D=l}function Yc(a,b,c){if(b.f())a.D=c,a.n=l;else if(a.D!==l)a.D=a.D.sa(b,c);else{a.n==l&&(a.n=new uc);var d=G(b);a.n.contains(d)||a.n.add(d,new Xc);a=a.n.get(d);b=Ka(b);Yc(a,b,c)}}function Zc(a,b){if(b.f())return a.D=l,a.n=l,k;if(a.D!==l){if(a.D.J())return o;var c=a.D;a.D=l;c.w(function(b,c){Yc(a,new K(b),c)});return Zc(a,b)}return a.n!==l?(c=G(b),b=Ka(b),a.n.contains(c)&&Zc(a.n.get(c),b)&&a.n.remove(c),a.n.f()?(a.n=l,k):o):k}
function $c(a,b,c){a.D!==l?c(b,a.D):a.w(function(a,e){var f=new K(b.toString()+"/"+a);$c(e,f,c)})}Xc.prototype.w=function(a){this.n!==l&&U(this.n,function(b,c){a(b,c)})};function ad(){this.za=Q}function V(a,b){return a.za.N(b)}function W(a,b,c){a.za=a.za.sa(b,c)}ad.prototype.toString=function(){return this.za.toString()};function bd(){this.Ba=new ad;this.G=new ad;this.ta=new ad;this.rb=new Na}function cd(a,b){for(var c=V(a.Ba,b),d=V(a.G,b),e=L(a.rb,b),f=o,h=e;h!==l;){if(h.j()!==l){f=k;break}h=h.parent()}if(f)return o;c=dd(c,d,e);return c!==d?(W(a.G,b,c),k):o}function dd(a,b,c){if(c.f())return a;if(c.j()!==l)return b;a=a||Q;c.w(function(d){var d=d.name(),e=a.O(d),f=b.O(d),h=L(c,d),e=dd(e,f,h);a=a.H(d,e)});return a}
bd.prototype.set=function(a,b){var c=this,d=[];hb(b,function(a){var b=a.path,a=a.Fa,h=Gb();M(L(c.rb,b),h);W(c.G,b,a);d.push({path:b,Hd:h})});return d};function ed(a,b){hb(b,function(b){var d=b.Hd,b=L(a.rb,b.path),e=b.j();z(e!==l,"pendingPut should not be null.");e===d&&M(b,l)})};function fd(){this.ka=[]}fd.prototype.Va=function(){for(var a=0;a<this.ka.length;a++)if(this.ka[a]){var b=this.ka[a];this.ka[a]=l;var c=b.ia;c(b.fd,b.tb)}this.ka=[]};function X(a,b,c,d){this.type=a;this.na=b;this.Y=c;this.tb=d};function gd(a){this.L=a;this.ja=[];this.nc=new fd}function hd(a,b,c,d,e){a.ja.push({type:b,ia:c,cancel:d,Z:e});var d=[],f=id(a.i);a.hb&&f.push(new X("value",a.i));for(var h=0;h<f.length;h++)if(f[h].type===b){var i=new J(a.L.u,a.L.path);f[h].Y&&(i=i.F(f[h].Y));d.push({ia:e?w(c,e):c,fd:new T(f[h].na,i),tb:f[h].tb})}a=a.nc;0!==d.length&&a.ka.push.apply(a.ka,d)}gd.prototype.Tb=function(a,b){b=this.Ub(a,b);b!=l&&jd(this,b)};
function jd(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],f=e.type,h=new J(a.L.u,a.L.path);b[d].Y&&(h=h.F(b[d].Y));h=new T(b[d].na,h);"value"===e.type&&!h.fb()?f+="("+h.T()+")":"value"!==e.type&&(f+=" "+h.name());P(a.L.u.o.id+": event:"+a.L.path+":"+a.L.Ia()+":"+f);for(f=0;f<a.ja.length;f++){var i=a.ja[f];b[d].type===i.type&&c.push({ia:i.Z?w(i.ia,i.Z):i.ia,fd:h,tb:e.tb})}}d=a.nc;0!==c.length&&d.ka.push.apply(d.ka,c)}gd.prototype.Va=function(){this.nc.Va()};
function id(a){var b=[];if(!a.J()){var c=l;a.w(function(a,e){b.push(new X("child_added",e,a,c));c=a})}return b}function kd(a){a.hb||(a.hb=k,jd(a,[new X("value",a.i)]))};function ld(a,b){gd.call(this,a);this.i=b}ja(ld,gd);ld.prototype.Ub=function(a,b){this.i=a;this.hb&&b!=l&&b.push(new X("value",this.i));return b};ld.prototype.eb=function(){return{}};function md(a,b){this.Hb=a;this.vc=b}
function nd(a,b,c,d,e){var f=a.N(c),h=b.N(c),d=new md(d,e),e=od(d,c,f,h),h=!f.f()&&!h.f()&&f.k()!==h.k();if(e||h){f=c;for(c=e;f.parent()!==l;){var i=a.N(f),e=b.N(f),m=f.parent();if(!d.Hb||L(d.Hb,m).j()){var n=b.N(m),p=[],f=f.W<f.m.length?f.m[f.m.length-1]:l;i.f()?(i=n.ca(f,e),p.push(new X("child_added",e,f,i))):e.f()?p.push(new X("child_removed",i,f)):(i=n.ca(f,e),h&&p.push(new X("child_moved",e,f,i)),c&&p.push(new X("child_changed",e,f,i)));d.vc(m,n,p)}h&&(h=o,c=k);f=m}}}
function od(a,b,c,d){var e,f=[];c===d?e=o:c.J()&&d.J()?e=c.j()!==d.j():c.J()?(pd(a,b,Q,d,f),e=k):d.J()?(pd(a,b,c,Q,f),e=k):e=pd(a,b,c,d,f);e?a.vc(b,d,f):c.k()!==d.k()&&a.vc(b,d,l);return e}
function pd(a,b,c,d,e){var f=o,h=!a.Hb||!L(a.Hb,b).f(),i=[],m=[],n=[],p=[],r={},s={},x,N,I,F;x=c.Pa();I=Va(x);N=d.Pa();for(F=Va(N);I!==l||F!==l;){c=I===l?1:F===l?-1:I.key===F.key?0:bc({name:I.key,ma:I.value.k()},{name:F.key,ma:F.value.k()});if(0>c)f=ta(r,I.key),u(f)?(n.push({pc:I,Jc:i[f]}),i[f]=l):(s[I.key]=m.length,m.push(I)),f=k,I=Va(x);else{if(0<c)f=ta(s,F.key),u(f)?(n.push({pc:m[f],Jc:F}),m[f]=l):(r[F.key]=i.length,i.push(F)),f=k;else{c=b.F(F.key);if(c=od(a,c,I.value,F.value))p.push(F),f=k;I.value.k()!==
F.value.k()&&(n.push({pc:I,Jc:F}),f=k);I=Va(x)}F=Va(N)}if(!h&&f)return k}for(h=0;h<m.length;h++)if(r=m[h])c=b.F(r.key),od(a,c,r.value,Q),e.push(new X("child_removed",r.value,r.key));for(h=0;h<i.length;h++)if(r=i[h])c=b.F(r.key),m=d.ca(r.key,r.value),od(a,c,Q,r.value),e.push(new X("child_added",r.value,r.key,m));for(h=0;h<n.length;h++)r=n[h].pc,i=n[h].Jc,c=b.F(i.key),m=d.ca(i.key,i.value),e.push(new X("child_moved",i.value,i.key,m)),(c=od(a,c,r.value,i.value))&&p.push(i);for(h=0;h<p.length;h++)a=p[h],
m=d.ca(a.key,a.value),e.push(new X("child_changed",a.value,a.key,m));return f};function qd(){this.Q=this.ra=l;this.set={}}ja(qd,uc);t=qd.prototype;t.setActive=function(a){this.ra=a};function rd(a){return a.contains("default")}function sd(a){return a.ra!=l&&rd(a)}t.defaultView=function(){return rd(this)?this.get("default"):l};t.path=aa("Q");t.toString=function(){return ib(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};t.Ua=function(){var a=[];U(this,function(b,c){a.push(c.L)});return a};function td(a,b){gd.call(this,a);this.i=Q;this.Ub(b,id(b))}ja(td,gd);
td.prototype.Ub=function(a,b){if(b===l)return b;var c=[],d=this.L;u(d.ba)&&(u(d.pa)&&d.pa!=l?c.push(function(a,b){var c=Rb(b,d.ba);return 0<c||0===c&&a>=d.pa}):c.push(function(a,b){return 0<=Rb(b,d.ba)}));u(d.va)&&(u(d.Oa)?c.push(function(a,b){var c=Rb(b,d.va);return 0>c||0===c&&a<=d.Oa}):c.push(function(a,b){return 0>=Rb(b,d.va)}));var e=l,f=l;if(u(this.L.xa))if(u(this.L.ba)){if(e=ud(a,c,this.L.xa,o)){var h=a.O(e).k();c.push(function(a,b){var c=Rb(b,h);return 0>c||0===c&&a<=e})}}else if(f=ud(a,c,
this.L.xa,k)){var i=a.O(f).k();c.push(function(a,b){var c=Rb(b,i);return 0<c||0===c&&a>=f})}for(var m=[],n=[],p=[],r=[],s=0;s<b.length;s++){var x=b[s].Y,N=b[s].na;switch(b[s].type){case "child_added":vd(c,x,N)&&(this.i=this.i.H(x,N),n.push(b[s]));break;case "child_removed":this.i.O(x).f()||(this.i=this.i.H(x,l),m.push(b[s]));break;case "child_changed":!this.i.O(x).f()&&vd(c,x,N)&&(this.i=this.i.H(x,N),r.push(b[s]));break;case "child_moved":var I=!this.i.O(x).f(),F=vd(c,x,N);I?F?(this.i=this.i.H(x,
N),p.push(b[s])):(m.push(new X("child_removed",this.i.O(x),x)),this.i=this.i.H(x,l)):F&&(this.i=this.i.H(x,N),n.push(b[s]))}}var Hc=e||f;if(Hc){var Ic=(s=f!==l)?this.i.Tc():this.i.Uc(),Zb=o,Wa=o,Xa=this;(s?a.oc:a.w).call(a,function(a,b){!Wa&&Ic===l&&(Wa=k);if(Wa&&Zb)return k;Zb?(m.push(new X("child_removed",Xa.i.O(a),a)),Xa.i=Xa.i.H(a,l)):Wa&&(n.push(new X("child_added",b,a)),Xa.i=Xa.i.H(a,b));Ic===a&&(Wa=k);a===Hc&&(Zb=k)})}for(s=0;s<n.length;s++)c=n[s],x=this.i.ca(c.Y,c.na),m.push(new X("child_added",
c.na,c.Y,x));for(s=0;s<p.length;s++)c=p[s],x=this.i.ca(c.Y,c.na),m.push(new X("child_moved",c.na,c.Y,x));for(s=0;s<r.length;s++)c=r[s],x=this.i.ca(c.Y,c.na),m.push(new X("child_changed",c.na,c.Y,x));this.hb&&0<m.length&&m.push(new X("value",this.i));return m};function ud(a,b,c,d){if(a.J())return l;var e=l;(d?a.oc:a.w).call(a,function(a,d){if(vd(b,a,d)&&(e=a,c--,0===c))return k});return e}function vd(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.k()))return o;return k}
td.prototype.qc=function(a){return this.i.O(a)!==Q};td.prototype.eb=function(a,b,c){var d={};this.i.J()||this.i.w(function(a){d[a]=k});var e=this.i,c=V(c,new K("")),f=new Na;M(L(f,this.L.path),k);var h=Q.sa(a,b),i=[];nd(c,h,a,f,function(a,b,c){c!==l&&(i=i.concat(c))});this.Ub(b,i);this.i.J()||this.i.w(function(a){d[a]=k});this.i=e;return d};function wd(a,b){this.o=a;this.g=b;this.tc=b.za;this.ha=new Na}
wd.prototype.Fb=function(a,b,c,d,e){var f=a.path,h=L(this.ha,f),i=h.j();i===l?(i=new qd,M(h,i)):z(!i.f(),"We shouldn't be storing empty QueryMaps");var m=a.Ia();if(i.contains(m))a=i.get(m),hd(a,b,c,d,e);else{var n=this.g.za.N(f),n=a="default"===a.Ia()?new ld(a,n):new td(a,n);if(sd(i)||xd(h))i.add(m,n),i.Q||(i.Q=n.L.path);else{var p,r;i.f()||(p=i.toString(),r=i.Ua());i.add(m,n);i.Q||(i.Q=n.L.path);i.setActive(yd(this,i));p&&r&&this.o.hd(i.path(),p,r)}sd(i)&&Pa(h,function(a){if(a=a.j()){a.ra&&a.ra();
a.ra=l}});hd(a,b,c,d,e);(b=(b=Qa(L(this.ha,f),function(a){var b;if(b=a.j())if(b=a.j().defaultView())b=a.j().defaultView().hb;if(b)return k},k))||this.o===l)&&kd(a)}a.Va()};function zd(a,b,c,d,e){var f=a.get(b),h;if(h=f){h=o;for(var i=f.ja.length-1;0<=i;i--){var m=f.ja[i];if((!c||m.type===c)&&(!d||m.ia===d)&&(!e||m.Z===e))if(f.ja.splice(i,1),h=k,c&&d)break}h=h&&!(0<f.ja.length)}(c=h)&&a.remove(b);return c}
wd.prototype.Xb=function(a,b,c,d){var e=L(this.ha,a.path).j();return e===l?l:Ad(this,e,a,b,c,d)};
function Ad(a,b,c,d,e,f){var h=b.path(),h=L(a.ha,h),c=c?c.Ia():l,i=[];c&&"default"!==c?zd(b,c,d,e,f)&&i.push(c):hb(b.keys(),function(a){zd(b,a,d,e,f)&&i.push(a)});b.f()&&M(h,l);c=xd(h);if(0<i.length&&!c){for(var m=h,n=h.parent(),c=o;!c&&n;){var p=n.j();if(p){z(!sd(p));var r=m.name(),s=o;U(p,function(a,b){s=b.qc(r)||s});s&&(c=k)}m=n;n=n.parent()}m=l;if(!sd(b)){n=b.ra;b.ra=l;var x=[],N=function(b){var c=b.j();if(c&&rd(c))x.push(c.path()),c.ra==l&&c.setActive(yd(a,c));else{if(c){c.ra!=l||c.setActive(yd(a,
c));var d={};U(c,function(a,b){b.i.w(function(a){D(d,a)||(d[a]=k,a=c.path().F(a),x.push(a))})})}b.w(N)}};N(h);m=x;n&&n()}return c?l:m}return l}function Bd(a,b,c){Pa(L(a.ha,b),function(a){(a=a.j())&&U(a,function(a,b){kd(b)})},c,k)}
function Cd(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return k;return o}var e=a.tc,f=a.g.za;a.tc=f;nd(e,f,b,a.ha,function(c,e,f){if(b.contains(c)){var n=d(c);n&&Bd(a,c,o);a.Tb(c,e,f);n&&Bd(a,c,k)}else a.Tb(c,e,f)});d(b)&&Bd(a,b,k);e=L(a.ha,b);Pa(e,function(a){(a=a.j())&&U(a,function(a,b){b.Va()})},k,k);Qa(e,function(a){(a=a.j())&&U(a,function(a,b){b.Va()})},o)}wd.prototype.Tb=function(a,b,c){a=L(this.ha,a).j();a!==l&&U(a,function(a,e){e.Tb(b,c)})};
function xd(a){return Qa(a,function(a){return a.j()&&sd(a.j())})}
function yd(a,b){if(a.o){var c=b.keys(),d=a.o,e=function(d){"ok"!==d?(Qb("on() or once() for "+b.path().toString()+" failed: "+d),b&&U(b,function(a,b){for(var c=0;c<b.ja.length;c++){var d=b.ja[c];d.cancel&&(d.Z?w(d.cancel,d.Z):d.cancel)()}}),Ad(a,b)):(hb(c,function(a){(a=b.get(a))&&kd(a)}),hb(c,function(a){(a=b.get(a))&&a.Va()}))},f=b.toString(),h=b.path().toString();d.ea[h]=d.ea[h]||{};z(!d.ea[h][f],"listen() called twice for same path/queryId.");d.ea[h][f]={Ua:b.Ua(),C:e};d.U&&Qc(d,h,f,b.Ua(),e);
return w(a.o.hd,a.o,b.path(),b.toString(),b.Ua())}return ca}wd.prototype.eb=function(a,b,c,d){var e={};U(b,function(b,h){var i=h.eb(a,c,d);Vb(i,function(a,b){e[b]=a?k:ta(e,b)||o})});c.J()||c.w(function(a){D(e,a)||(e[a]=o)});return e};
function Dd(a,b,c,d,e,f){var h=b.path();if(f!==l){var i=[];d.J()||d.w(function(a,b){i.push({path:h.F(a),Fa:b});delete f[a]});Vb(f,function(a,b){i.push({path:h.F(b),Fa:Q})});return i}var b=a.eb(h,b,d,e),m=Q,n=[];Vb(b,function(b,f){var h=new K(f);b?m=m.H(f,d.N(h)):n=n.concat(Ed(a,d.N(h),L(c,h),e))});return[{path:h,Fa:m}].concat(n)}
function Fd(a,b,c,d,e){for(var f=L(a.ha,b),h=f.parent(),i=o;!i&&h!==l;){var m=h.j();m!==l&&(rd(m)?i=k:(m=a.eb(b,m,c,d),f=f.name(),ta(m,f)&&(i=k)));f=h;h=h.parent()}if(i)return[{path:b,Fa:c}];h=L(a.ha,b);i=h.j();return i!==l?rd(i)?[{path:b,Fa:c}]:Dd(a,i,h,c,d,e):Ed(a,c,h,d)}function Ed(a,b,c,d){var e=c.j();if(e!==l)return rd(e)?[{path:c.path(),Fa:b}]:Dd(a,e,c,b,d,l);var f=[];c.w(function(c){var e=b.J()?Q:b.O(c.name()),c=Ed(a,e,c,d);f=f.concat(c)});return f};function Gd(a){this.R=a;this.X=oc(a);this.o=new Nc(this.R,w(this.Ob,this),w(this.Mb,this),w(this.mb,this),w(this.zc,this));var b=w(function(){return new lc(this.X,this.o)},this),a=a.toString();nc[a]||(nc[a]=b());this.gd=nc[a];this.Ya=new Na;this.Za=new ad;this.g=new bd;this.M=new wd(this.o,this.g.ta);this.rc=new ad;this.sc=new wd(l,this.rc);Hd(this,"connected",o);Hd(this,"authenticated",o);Hd(this,"serverTimeOffset",l);this.P=new Xc}t=Gd.prototype;
t.toString=function(){return(this.R.Zb?"https://":"http://")+this.R.host};t.name=function(){return this.R.lb};
t.Ob=function(a,b,c){var d,e=[];if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new K(a.substring(0,a.length-9)),d=V(this.g.Ba,a).Db(b),e.push(a);else if(c){a=new K(a);d=V(this.g.Ba,a);for(var f in b){var h=new K(f);d=d.sa(h,S(b[f]));e.push(a.F(f))}}else a=new K(a),d=S(b),e.push(a);b=Fd(this.M,a,d,this.g.G,c?b:l);c=o;for(f=0;f<b.length;++f){d=b[f];var h=this.g,i=d.path;W(h.Ba,i,d.Fa);c=cd(h,i)||c}c&&(a=Id(this,a));Cd(this.M,a,e)};
t.Mb=function(a){Hd(this,"connected",a);if(a===o){this.e("onDisconnectEvents");var b=this,c=[];$c(this.P,new K(""),function(a,e){var f=Fd(b.M,a,e,b.g.G,l);c.push.apply(c,b.g.set(a,f));f=Jd(b,a);Id(b,f);Cd(b.M,f,[a])});ed(this.g,c);this.P=new Xc}};t.zc=function(a){var b=this;Ub(a,function(a,d){Hd(b,d,a)})};t.mb=function(a){Hd(this,"authenticated",a)};function Hd(a,b,c){b=new K("/.info/"+b);W(a.rc,b,S(c));Cd(a.sc,b,[b])}
t.$a=function(a,b,c){this.o.$a(a,function(a,c){Kd(b,a,c)},function(a,b){Qb("auth() was canceled: "+b);if(c){var f=Error(b);f.code=a.toUpperCase();c(f)}})};t.Cb=function(){this.o.Cb()};t.Xa=function(a,b,c,d){this.e("set",{path:a.toString(),value:b});var b=S(b,c),c=Fd(this.M,a,b,this.g.G,l),e=this.g.set(a,c),f=this;this.o.put(a.toString(),b.T(k),function(b){var c="ok"===b;ed(f.g,e);c||(Qb("set at "+a+" failed: "+b),cd(f.g,a),c=Id(f,a),Cd(f.M,c,[]));Kd(d,b)});b=Jd(this,a);Id(this,b);Cd(this.M,b,[a])};
t.update=function(a,b,c){this.e("update",{path:a.toString(),value:b});var d=V(this.g.ta,a),e=k,f=[],h;for(h in b){var e=o,i=S(b[h]),d=d.H(h,i);f.push(a.F(h))}if(e)P("update() called with empty data.  Don't do anything."),Kd(c,"ok");else{var d=Fd(this.M,a,d,this.g.G,b),m=this.g.set(a,d),n=this;Vc(this.o,"m",a.toString(),b,function(b){z("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");ed(n.g,m);Kd(c,b)},j);b=Jd(this,a);Id(this,b);Cd(n.M,b,f)}};
t.Fc=function(a,b,c){this.e("setPriority",{path:a.toString(),ma:b});var d=V(this.g.G,a).Db(b),d=Fd(this.M,a,d,this.g.G,l),e=this.g.set(a,d),f=this;this.o.put(a.toString()+"/.priority",b,function(a){ed(f.g,e);Kd(c,a)});a=Id(this,a);Cd(f.M,a,[])};t.wc=function(a,b){var c=this;this.o.wc(a.toString(),function(d){"ok"===d&&Zc(c.P,a);Kd(b,d)})};function Ld(a,b,c,d){var e=S(c);Tc(a.o,b.toString(),e.T(k),function(c){"ok"===c&&Yc(a.P,b,e);Kd(d,c)})}
function Md(a){jc(a.X,"deprecated_on_disconnect");a.gd.Ic.deprecated_on_disconnect=k}t.Fb=function(a,b,c,d,e){".info"===G(a.path)?this.sc.Fb(a,b,c,d,e):this.M.Fb(a,b,c,d,e)};t.Xb=function(a,b,c,d){if(".info"===G(a.path))this.sc.Xb(a,b,c,d);else{b=this.M.Xb(a,b,c,d);if(c=b!==l){for(var c=this.g,d=a.path,e=[],f=0;f<b.length;++f)e[f]=V(c.Ba,b[f]);W(c.Ba,d,Q);for(f=0;f<b.length;++f)W(c.Ba,b[f],e[f]);c=cd(c,d)}c&&(W(this.g.ta,a.path,V(this.g.G,a.path)),this.M.tc=this.g.ta.za)}};t.Qa=function(){this.o.Qa()};
t.xb=function(){this.o.xb()};t.Gc=function(a){if("undefined"!==typeof console){a?(this.bc||(this.bc=new kc(this.X)),a=this.bc.get()):a=this.X.get();var b=a,c=[],d=0,e;for(e in b)c[d++]=e;var f=function(a,b){return Math.max(b.length,a)};if(c.reduce)e=c.reduce(f,0);else{var h=0;hb(c,function(a){h=f.call(j,h,a)});e=h}for(var i in a){b=a[i];for(c=i.length;c<e+2;c++)i+=" ";console.log(i+b)}}};t.Hc=function(a){jc(this.X,a);this.gd.Ic[a]=k};t.e=function(){P("r:"+this.o.id+":",arguments)};
function Kd(a,b,c){if(a)if("ok"==b)a(l,c);else{var d=b=(b||"error").toUpperCase();c&&(d+=": "+c);c=Error(d);c.code=b;a(c)}};function Nd(a,b){var c=b||a.Ya;b||Od(a,c);if(c.j()!==l){var d=Pd(a,c);z(0<d.length);if(2!==d[0].status&&4!==d[0].status){for(var e=c.path(),f=0;f<d.length;f++)z(1===d[f].status,"tryToSendTransactionQueue_: items in queue should all be run."),d[f].status=2,d[f].ed++;c=V(a.g.G,e).hash();W(a.g.G,e,V(a.g.ta,e));for(var h=V(a.Za,e).T(k),i=Gb(),m={},n=0;n<d.length;n++)d[n].hc&&(m[d[n].path.toString()]=d[n].path);var p=[],r;for(r in m)p.push(m[r]);for(f=0;f<p.length;f++)M(L(a.g.rb,p[f]),i);a.o.put(e.toString(),
h,function(b){a.e("transaction put response",{path:e.toString(),status:b});for(f=0;f<p.length;f++){var c=L(a.g.rb,p[f]),h=c.j();z(h!==l,"sendTransactionQueue_: pendingPut should not be null.");h===i&&(M(c,l),W(a.g.G,p[f],V(a.g.Ba,p[f])))}if("ok"===b){b=[];for(f=0;f<d.length;f++)d[f].status=3,d[f].C&&(c=Qd(a,d[f].path),b.push(w(d[f].C,l,l,k,c))),d[f].ec();Od(a,L(a.Ya,e));Nd(a);for(f=0;f<b.length;f++)b[f]()}else{if("datastale"===b)for(f=0;f<d.length;f++)d[f].status=4===d[f].status?5:1;else{Qb("transaction at "+
e+" failed: "+b);for(f=0;f<d.length;f++)d[f].status=5,d[f].fc=b}b=Id(a,e);Cd(a.M,b,[e])}},c)}}else c.fb()&&c.w(function(b){Nd(a,b)})}
function Id(a,b){var c=Rd(a,b),d=c.path(),e=Pd(a,c);W(a.g.ta,d,V(a.g.G,d));W(a.Za,d,V(a.g.G,d));if(0!==e.length){for(var f=c=V(a.g.ta,d),h=[],i=0;i<e.length;i++){var m=La(d,e[i].path),n=o,p;z(m!==l,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===e[i].status)n=k,p=e[i].fc;else if(1===e[i].status)if(25<=e[i].ed)n=k,p="maxretry";else{var r=e[i].update(c.N(m).T());u(r)?(za("transaction failed: Data returned ",r),r=S(r),c=c.sa(m,r),e[i].hc&&(f=f.sa(m,r))):(n=k,p="nodata")}n&&(e[i].ec(),
e[i].status=3,e[i].C&&(n=new J(a,e[i].path),m=new T(c.N(m),n),"nodata"===p?h.push(w(e[i].C,l,l,o,m)):h.push(w(e[i].C,l,Error(p),o,m))))}p=V(a.g.G,d).k();c=c.Db(p);f=f.Db(p);W(a.Za,d,c);W(a.g.ta,d,f);Od(a,a.Ya);for(i=0;i<h.length;i++)h[i]();Nd(a)}return d}function Rd(a,b){for(var c,d=a.Ya;(c=G(b))!==l&&d.j()===l;)d=L(d,c),b=Ka(b);return d}function Pd(a,b){var c=[];Sd(a,b,c);c.sort(function(a,b){return a.Zc-b.Zc});return c}
function Sd(a,b,c){var d=b.j();if(d!==l)for(var e=0;e<d.length;e++)c.push(d[e]);b.w(function(b){Sd(a,b,c)})}function Od(a,b){var c=b.j();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;M(b,0<c.length?c:l)}b.w(function(b){Od(a,b)})}function Jd(a,b){var c=Rd(a,b).path(),d=L(a.Ya,b);Qa(d,function(a){Td(a)});Td(d);Pa(d,function(a){Td(a)});return c}
function Td(a){var b=a.j();if(b!==l){for(var c=[],d=-1,e=0;e<b.length;e++)4!==b[e].status&&(2===b[e].status?(z(d===e-1,"All SENT items should be at beginning of queue."),d=e,b[e].status=4,b[e].fc="set"):(z(1===b[e].status),b[e].ec(),b[e].C&&c.push(w(b[e].C,l,Error("set"),o,l))));-1===d?M(a,l):b.length=d+1;for(e=0;e<c.length;e++)c[e]()}}function Qd(a,b){var c=new J(a,b);return new T(V(a.Za,b),c)};function Y(){this.Wa={}}Y.ud=function(){return Y.Vc?Y.Vc:Y.Vc=new Y};Y.prototype.Qa=function(){for(var a in this.Wa)this.Wa[a].Qa()};Y.prototype.interrupt=Y.prototype.Qa;Y.prototype.xb=function(){for(var a in this.Wa)this.Wa[a].xb()};Y.prototype.resume=Y.prototype.xb;var Z={vd:function(a){var b=R.prototype.hash;R.prototype.hash=a;var c=Xb.prototype.hash;Xb.prototype.hash=a;return function(){R.prototype.hash=b;Xb.prototype.hash=c}}};Z.hijackHash=Z.vd;Z.Ia=function(a){return a.Ia()};Z.queryIdentifier=Z.Ia;Z.xd=function(a){return a.u.o.ea};Z.listens=Z.xd;Z.Dd=function(a){return a.u.o.ub};Z.refConnection=Z.Dd;Z.kd=Nc;Z.DataConnection=Z.kd;Nc.prototype.sendRequest=Nc.prototype.Aa;Nc.prototype.interrupt=Nc.prototype.Qa;Z.ld=Fc;Z.RealTimeConnection=Z.ld;
Fc.prototype.sendRequest=Fc.prototype.Ec;Fc.prototype.close=Fc.prototype.close;Z.jd=pb;Z.ConnectionTarget=Z.jd;Z.sd=function(){yc=rc=k};Z.forceLongPolling=Z.sd;Z.td=function(){zc=k};Z.forceWebSockets=Z.td;Z.Jd=function(a,b){a.u.o.Dc=b};Z.setSecurityDebugCallback=Z.Jd;Z.Gc=function(a,b){a.u.Gc(b)};Z.stats=Z.Gc;Z.Hc=function(a,b){a.u.Hc(b)};Z.statsIncrementCounter=Z.Hc;function $(a,b,c){this.vb=a;this.Q=b;this.ya=c}$.prototype.cancel=function(a){A("Firebase.onDisconnect().cancel",0,1,arguments.length);C("Firebase.onDisconnect().cancel",1,a,k);this.vb.wc(this.Q,a)};$.prototype.cancel=$.prototype.cancel;$.prototype.remove=function(a){A("Firebase.onDisconnect().remove",0,1,arguments.length);E("Firebase.onDisconnect().remove",this.Q);C("Firebase.onDisconnect().remove",1,a,k);Ld(this.vb,this.Q,l,a)};$.prototype.remove=$.prototype.remove;
$.prototype.set=function(a,b){A("Firebase.onDisconnect().set",1,2,arguments.length);E("Firebase.onDisconnect().set",this.Q);ya("Firebase.onDisconnect().set",a,o);C("Firebase.onDisconnect().set",2,b,k);Ld(this.vb,this.Q,a,b)};$.prototype.set=$.prototype.set;
$.prototype.Xa=function(a,b,c){A("Firebase.onDisconnect().setWithPriority",2,3,arguments.length);E("Firebase.onDisconnect().setWithPriority",this.Q);ya("Firebase.onDisconnect().setWithPriority",a,o);Da("Firebase.onDisconnect().setWithPriority",2,b,o);C("Firebase.onDisconnect().setWithPriority",3,c,k);(".length"===this.ya||".keys"===this.ya)&&g("Firebase.onDisconnect().setWithPriority failed: "+this.ya+" is a read-only object.");var d=this.vb,e=this.Q,f=S(a,b);Tc(d.o,e.toString(),f.T(k),function(a){"ok"===
a&&Yc(d.P,e,f);Kd(c,a)})};$.prototype.setWithPriority=$.prototype.Xa;
$.prototype.update=function(a,b){A("Firebase.onDisconnect().update",1,2,arguments.length);E("Firebase.onDisconnect().update",this.Q);Ca("Firebase.onDisconnect().update",a);C("Firebase.onDisconnect().update",2,b,k);var c=this.vb,d=this.Q,e=k,f;for(f in a)e=o;if(e)P("onDisconnect().update() called with empty data.  Don't do anything."),Kd(b,k);else{e=c.o;f=d.toString();var h=function(e){if("ok"===e)for(var f in a){var h=S(a[f]);Yc(c.P,d.F(f),h)}Kd(b,e)};e.U?Uc(e,"om",f,a,h):e.nb.push({Bc:f,action:"om",
data:a,C:h})}};$.prototype.update=$.prototype.update;var Ud,Vd=0,Wd=[];Ud=function(a){var b=a===Vd;Vd=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);z(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===Wd[d];d--)Wd[d]=0;Wd[d]++}else for(d=0;12>d;d++)Wd[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(Wd[d]);z(20===a.length,"NextPushId: Length should be 20.");return a};function J(){var a,b,c;if(arguments[0]instanceof Gd)c=arguments[0],a=arguments[1];else{A("new Firebase",1,2,arguments.length);var d=arguments[0];b=a="";var e=k,f="";if(v(d)){var h=d.indexOf("//");if(0<=h)var i=d.substring(0,h-1),d=d.substring(h+2);h=d.indexOf("/");-1===h&&(h=d.length);a=d.substring(0,h);var d=d.substring(h+1),m=a.split(".");if(3==m.length){h=m[2].indexOf(":");e=0<=h?"https"===i:k;if("firebase"===m[1])Pb(a+" is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead");
else{b=m[0];f="";d=("/"+d).split("/");for(i=0;i<d.length;i++)if(0<d[i].length){h=d[i];try{h=decodeURIComponent(h.replace(/\+/g," "))}catch(n){}f+="/"+h}}b=b.toLowerCase()}else b=l}e||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&Qb("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new pb(a,e,b);b=new K(f);e=b.toString();if(!(d=!v(a.host)))if(!(d=0===a.host.length))if(!(d=!xa(a.lb)))if(d=
0!==e.length)e&&(e=e.replace(/^\/*\.info(\/|$)/,"/")),d=!(v(e)&&0!==e.length&&!wa.test(e));d&&g(Error(B("new Firebase",1,o)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Y?c=arguments[1]:g(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Y.ud();e=a.toString();d=ta(c.Wa,e);d||(d=new Gd(a),c.Wa[e]=d);c=d;a=b}H.call(this,c,a)}ja(J,H);var Xd=J,Yd=["Firebase"],Zd=ba;
!(Yd[0]in Zd)&&Zd.execScript&&Zd.execScript("var "+Yd[0]);for(var $d;Yd.length&&($d=Yd.shift());)!Yd.length&&u(Xd)?Zd[$d]=Xd:Zd=Zd[$d]?Zd[$d]:Zd[$d]={};J.prototype.name=function(){A("Firebase.name",0,0,arguments.length);return this.path.f()?l:this.path.W<this.path.m.length?this.path.m[this.path.m.length-1]:l};J.prototype.name=J.prototype.name;
J.prototype.F=function(a){A("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof K))if(G(this.path)===l){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Ga("Firebase.child",b)}else Ga("Firebase.child",a);return new J(this.u,this.path.F(a))};J.prototype.child=J.prototype.F;J.prototype.parent=function(){A("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===l?l:new J(this.u,a)};J.prototype.parent=J.prototype.parent;
J.prototype.root=function(){A("Firebase.ref",0,0,arguments.length);for(var a=this;a.parent()!==l;)a=a.parent();return a};J.prototype.root=J.prototype.root;J.prototype.toString=function(){var a;if(this.parent()===l)a=this.u.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};J.prototype.toString=J.prototype.toString;
J.prototype.set=function(a,b){A("Firebase.set",1,2,arguments.length);E("Firebase.set",this.path);ya("Firebase.set",a,o);C("Firebase.set",2,b,k);return this.u.Xa(this.path,a,l,b)};J.prototype.set=J.prototype.set;J.prototype.update=function(a,b){A("Firebase.update",1,2,arguments.length);E("Firebase.update",this.path);Ca("Firebase.update",a);C("Firebase.update",2,b,k);return this.u.update(this.path,a,b)};J.prototype.update=J.prototype.update;
J.prototype.Xa=function(a,b,c){A("Firebase.setWithPriority",2,3,arguments.length);E("Firebase.setWithPriority",this.path);ya("Firebase.setWithPriority",a,o);Da("Firebase.setWithPriority",2,b,o);C("Firebase.setWithPriority",3,c,k);(".length"===this.name()||".keys"===this.name())&&g("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.u.Xa(this.path,a,b,c)};J.prototype.setWithPriority=J.prototype.Xa;
J.prototype.remove=function(a){A("Firebase.remove",0,1,arguments.length);E("Firebase.remove",this.path);C("Firebase.remove",1,a,k);this.set(l,a)};J.prototype.remove=J.prototype.remove;
J.prototype.transaction=function(a,b,c){function d(){}A("Firebase.transaction",1,3,arguments.length);E("Firebase.transaction",this.path);C("Firebase.transaction",1,a,o);C("Firebase.transaction",2,b,k);u(c)&&"boolean"!=typeof c&&g(Error(B("Firebase.transaction",3,k)+"must be a boolean."));(".length"===this.name()||".keys"===this.name())&&g("Firebase.transaction failed: "+this.name()+" is a read-only object.");"undefined"===typeof c&&(c=k);var e=this.u,f=this.path,h=c;e.e("transaction on "+f);var i=
new J(e,f);i.uc("value",d);var h={path:f,update:a,C:b,status:l,Zc:Gb(),hc:h,ed:0,ec:function(){i.Lb("value",d)},fc:l},m=h.update(V(e.Za,f).T());if(u(m)){za("transaction failed: Data returned ",m);h.status=1;var n=L(e.Ya,f),p=n.j()||[];p.push(h);M(n,p);n=V(e.g.G,f).k();W(e.Za,f,S(m,n));h.hc&&(W(e.g.ta,f,S(m,n)),Cd(e.M,f,[f]));Nd(e)}else h.ec(),h.C&&(e=Qd(e,f),h.C(l,o,e))};J.prototype.transaction=J.prototype.transaction;
J.prototype.Fc=function(a,b){A("Firebase.setPriority",1,2,arguments.length);E("Firebase.setPriority",this.path);Da("Firebase.setPriority",1,a,o);C("Firebase.setPriority",2,b,k);this.u.Fc(this.path,a,b)};J.prototype.setPriority=J.prototype.Fc;
J.prototype.push=function(a,b){A("Firebase.push",0,2,arguments.length);E("Firebase.push",this.path);ya("Firebase.push",a,k);C("Firebase.push",2,b,k);var c=V(this.u.rc,new K(".info/serverTimeOffset")).T()||0,c=Ud((new Date).getTime()+c),c=this.F(c);"undefined"!==typeof a&&a!==l&&c.set(a,b);return c};J.prototype.push=J.prototype.push;J.prototype.fa=function(){return new $(this.u,this.path,this.name())};J.prototype.onDisconnect=J.prototype.fa;
J.prototype.Ed=function(){Qb("FirebaseRef.removeOnDisconnect() being deprecated. Please use FirebaseRef.onDisconnect().remove() instead.");this.fa().remove();Md(this.u)};J.prototype.removeOnDisconnect=J.prototype.Ed;J.prototype.Id=function(a){Qb("FirebaseRef.setOnDisconnect(value) being deprecated. Please use FirebaseRef.onDisconnect().set(value) instead.");this.fa().set(a);Md(this.u)};J.prototype.setOnDisconnect=J.prototype.Id;
J.prototype.$a=function(a,b,c){A("Firebase.auth",1,3,arguments.length);v(a)||g(Error(B("Firebase.auth",1,o)+"must be a valid credential (a string)."));C("Firebase.auth",2,b,k);C("Firebase.auth",3,b,k);this.u.$a(a,b,c)};J.prototype.auth=J.prototype.$a;J.prototype.Cb=function(){this.u.Cb()};J.prototype.unauth=J.prototype.Cb;
function Mb(a,b){z(!b||a===k||a===o,"Can't turn on custom loggers persistently.");a===k?("undefined"!==typeof console&&("function"===typeof console.log?Kb=w(console.log,console):"object"===typeof console.log&&(Kb=function(a){console.log(a)})),b&&nb.setItem("logging_enabled","true")):a?Kb=a:(Kb=l,nb.removeItem("logging_enabled"))}J.enableLogging=Mb;J.INTERNAL=Z;J.Context=Y;})();
